

""" INICIO SECCIÓN ASOCIADA DEFINICIÓN DE FUNCIONES PARA PROCESAMIENTO DATA SENSOR  """

# NOTA: OUTPUT DEL SENSOR ESTÁ ASOCIADO A MEDIDAS EN 'lux'
# XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

